spring:
  application:
    name: fxflow
  profiles:
    include: secret

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always

exchange:
  fee:
    rates:
      KRW-USD: 0.001
      USD-KRW: 0.001
  quote-expiration-minutes: 5